### PR TITLE
add README for NUC stress testing

### PR DESCRIPTION
**Pull request by fmessmer**
ref. https://github.com/mojin-robotics/cob4/issues/1082

this is a first draft so far

@benmaidel @floweisshardt @HannesBachter @Acuda @LoyVanBeek @mojin-BUB 
please comment additional commands that might be helpful to detect/investigate NUC hardware issues...
...I will then extend the README

### CODE REVIEW

**Comment by LoyVanBeek** [comment]
Oops, I added cpu freq directly instead of commenting. If I have more, I'll post them here instead.

**Comment by fmessmer** [comment]
I still would like to head @benmaidel and maybe @Acuda's input given their experience of recent NUC debugging

**Comment by Acuda** [comment]
`mpstat` Report processors related statistics.
The  mpstat command writes to standard output activities for each available processor, processor 0 being the first one.

Status-Listing (e.g. for CPU-Load Problems)
`top -H` then sort for Status by pressing: `f`, on S = Process Status press `S`, then `Q`

Sometimes a Snapshoot of the processes is better then an updating `htop` or `top` (both should also be listed for completeness): `ps fax`

`dmesg` or `dmesg -w` with `-w` option for follow mode for changes

`sudo iftop -i <interface>` network-top

**Comment by fmessmer** [comment]
the mentioned tools are installed via https://github.com/mojin-robotics/setup_cob4/pull/155

**Comment by Acuda** [comment]
if possible add the description from "Status-Listing (e.g. for CPU-Load Problems)" to the readme. due to the fact it's not that intuitive to get the relevant view

**Pull request merged**
